# Generated by Django 4.2.3 on 2023-08-06 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(default='', max_length=100)),
                ('department_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='patientprofile/')),
                ('dob', models.DateField(max_length=14, null=True)),
                ('address', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('symptoms', models.CharField(max_length=100)),
                ('assignedDoctorId', models.PositiveIntegerField(null=True)),
                ('admitDate', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('mobileno', models.CharField(max_length=13)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(null=True, upload_to='doctorprofile/')),
                ('mobileno', models.CharField(max_length=13, null=True)),
                ('dob', models.DateField(max_length=14, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=30, null=True)),
                ('status', models.BooleanField(default=False)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='novapp.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(max_length=50)),
                ('age', models.PositiveBigIntegerField()),
                ('appointmentBookDate', models.DateField(auto_now_add=True)),
                ('appointmentDate', models.DateField()),
                ('message', models.TextField(max_length=500)),
                ('address', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('mobileno', models.CharField(max_length=13, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novapp.department')),
                ('doctorName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novapp.doctor')),
            ],
        ),
    ]
