# Generated by Django 4.2.3 on 2023-08-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novapp', '0002_appointment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
    ]
