# Generated by Django 4.2.3 on 2023-08-06 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novapp', '0004_remove_appointment_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='address',
        ),
    ]
