# Generated by Django 4.2.1 on 2023-08-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novapp', '0006_alter_department_department_status_alter_patient_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(max_length=14, null=True),
        ),
    ]
