# Generated by Django 4.2.1 on 2023-08-07 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novapp', '0007_alter_patient_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(null=True, upload_to='adminprofile/')),
                ('mobileno', models.CharField(max_length=13, null=True)),
                ('dob', models.DateField(max_length=14, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('country', models.CharField(max_length=30, null=True)),
                ('institution', models.CharField(max_length=30, null=True)),
                ('subject', models.CharField(max_length=30, null=True)),
                ('start_date', models.DateField(max_length=14, null=True)),
                ('complete_date', models.DateField(max_length=14, null=True)),
                ('degree', models.CharField(max_length=14, null=True)),
                ('percentage', models.FloatField(max_length=10, null=True)),
                ('company_name', models.CharField(max_length=20, null=True)),
                ('location', models.CharField(max_length=20, null=True)),
                ('job_position', models.CharField(max_length=20, null=True)),
                ('Period_from', models.DateField()),
                ('Period_to', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
